// <auto-generated />
using System;
using ElMolino.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElMolino.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260304044408_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ElMolino.Domain.Entities.EstadoCuenta", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPersona")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pagado")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdPersona");

                    b.ToTable("EstadosCuenta");
                });

            modelBuilder.Entity("ElMolino.Domain.Entities.Incidente", b =>
                {
                    b.Property<int>("IdIncidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostoReparacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionDano")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdReserva")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdIncidente");

                    b.HasIndex("IdReserva");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("ElMolino.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUnidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdPersona");

                    b.HasIndex("IdUnidad");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            IdPersona = 1,
                            Documento = "0000000000",
                            Email = "admin@elmolino.com",
                            Estado = 1,
                            IdUnidad = 1,
                            NombreCompleto = "Super Admin",
                            PasswordHash = "$2a$11$Kk3H1F15C6/i2.zVq4TExuXQQz.s/I3XkYlI5Rzv1P.K/P8D.KyyO",
                            Rol = "Administrador"
                        },
                        new
                        {
                            IdPersona = 2,
                            Documento = "1111111111",
                            Email = "juan@residente.com",
                            Estado = 1,
                            IdUnidad = 2,
                            NombreCompleto = "Juan Perez",
                            PasswordHash = "$2a$11$Kk3H1F15C6/i2.zVq4TExuXQQz.s/I3XkYlI5Rzv1P.K/P8D.KyyO",
                            Rol = "Residente"
                        },
                        new
                        {
                            IdPersona = 3,
                            Documento = "2222222222",
                            Email = "pedro@residente.com",
                            Estado = 0,
                            IdUnidad = 2,
                            NombreCompleto = "Pedro Inactivo",
                            PasswordHash = "$2a$11$Kk3H1F15C6/i2.zVq4TExuXQQz.s/I3XkYlI5Rzv1P.K/P8D.KyyO",
                            Rol = "Residente"
                        });
                });

            modelBuilder.Entity("ElMolino.Domain.Entities.Recurso", b =>
                {
                    b.Property<int>("IdRecurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostoPorReserva")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoFisico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdRecurso");

                    b.ToTable("Recursos");

                    b.HasData(
                        new
                        {
                            IdRecurso = 1,
                            CostoPorReserva = 10000m,
                            EstadoFisico = "Disponible",
                            Nombre = "Piscina Principal",
                            Tipo = "Zona Humeda"
                        },
                        new
                        {
                            IdRecurso = 2,
                            CostoPorReserva = 50000m,
                            EstadoFisico = "Disponible",
                            Nombre = "Salon Comunal",
                            Tipo = "Espacio Cerrado"
                        });
                });

            modelBuilder.Entity("ElMolino.Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoReserva")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPersona")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRecurso")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdRecurso");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("ElMolino.Domain.Entities.Unidad", b =>
                {
                    b.Property<int>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BloqueTorre")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroUnidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUnidad");

                    b.ToTable("Unidades");

                    b.HasData(
                        new
                        {
                            IdUnidad = 1,
                            BloqueTorre = "Edificio Central",
                            NumeroUnidad = "A-101"
                        },
                        new
                        {
                            IdUnidad = 2,
                            BloqueTorre = "Edificio Central",
                            NumeroUnidad = "A-102"
                        });
                });

            modelBuilder.Entity("ElMolino.Domain.Entities.EstadoCuenta", b =>
                {
                    b.HasOne("ElMolino.Domain.Entities.Persona", "Persona")
                        .WithMany("EstadosCuenta")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ElMolino.Domain.Entities.Incidente", b =>
                {
                    b.HasOne("ElMolino.Domain.Entities.Reserva", "Reserva")
                        .WithMany("Incidentes")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ElMolino.Domain.Entities.Persona", b =>
                {
                    b.HasOne("ElMolino.Domain.Entities.Unidad", "Unidad")
                        .WithMany("Personas")
                        .HasForeignKey("IdUnidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("ElMolino.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("ElMolino.Domain.Entities.Persona", "Persona")
                        .WithMany("Reservas")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElMolino.Domain.Entities.Recurso", "Recurso")
                        .WithMany("Reservas")
                        .HasForeignKey("IdRecurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("ElMolino.Domain.Entities.Persona", b =>
                {
                    b.Navigation("EstadosCuenta");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ElMolino.Domain.Entities.Recurso", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ElMolino.Domain.Entities.Reserva", b =>
                {
                    b.Navigation("Incidentes");
                });

            modelBuilder.Entity("ElMolino.Domain.Entities.Unidad", b =>
                {
                    b.Navigation("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
